#!/bin/bash
#ip link add link eth1 dev peth1 type macvlan
#ifconfig peth1 hw ether 54:98:02:43:49:86
#brctl addbr br0
#brctl addif br0 eth0
#brctl addif br0 peth1
ifconfig eth0 down
ifconfig eth1 172.16.55.91 netmask 255.255.255.0 up 
route add default gw 172.16.55.254
echo "nameserver 172.16.53.2" >/etc/resolv.conf
echo "nameserver 172.16.53.15" >>/etc/resolv.conf

echo "Start firewall"

/sbin/depmod -a
/sbin/modprobe ip_tables
/sbin/modprobe ip_conntrack
/sbin/modprobe iptable_filter
/sbin/modprobe iptable_mangle
/sbin/modprobe iptable_nat
/sbin/modprobe ipt_LOG
/sbin/modprobe ipt_limit
/sbin/modprobe ipt_state
echo "1" > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -s 172.16.55.90 -o  eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.131 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.132 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.133 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.134 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.135 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.136 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.138 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.143 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.220 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.224 -o eth1 -j SNAT --to 172.16.55.91
iptables -t nat -A POSTROUTING -s 172.16.55.226 -o eth1 -j SNAT --to 172.16.55.91


